# Welcome to Jekyll!
#

# Site settings
title: mfbx9da4
description: |
  Luxury software development services
owner: Mfbx9da4 LTD # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: dalberto.adler@gmail.com
social:
  github: https://github.com/mfbx9da4LTD
  facebook-official: https://www.facebook.com/Mfbx9da4-1017022458417360
  # twitter: https://twitter.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
